#ifndef PROTOCOL_H
#define PROTOCOL_H
typedef unsigned int uint;
enum ENUM_MSG_TYPE{//消息类型枚举值
    ENUM_MSG_TYPE_MIN=0,
    ENUM_MSG_TYPE_REGIST_REQUEST,
    ENUM_MSG_TYPE_REGIST_RESPOND,
    ENUM_MSG_TYPE_LOGIN_REQUEST,
    ENUM_MSG_TYPE_LOGIN_RESPOND,
    ENUM_MSG_TYPE_FIND_USER_REQUEST,
    ENUM_MSG_TYPE_FIND_USER_RESPOND,
    ENUM_MSG_TYPE_ONLINE_USER_REQUEST,
    ENUM_MSG_TYPE_ONLINE_USER_RESPOND,
    ENUM_MSG_TYPE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_REQUEST,
    ENUM_MSG_TYPE_AGREE_ADD_FRIEND_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FRIEND_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FRIEND_RESPOND,
    ENUM_MSG_TYPE_DELETE_FRIEND_REQUEST,
    ENUM_MSG_TYPE_DELETE_FRIEND_RESPOND,
    ENUM_MSG_TYPE_CHAT_REQUEST,
    ENUM_MSG_TYPE_CHAT_RESPOND,
    ENUM_MSG_TYPE_MKDIR_REQUEST,
    ENUM_MSG_TYPE_MKDIR_RESPOND,
    ENUM_MSG_TYPE_FLUSH_FILE_REQUEST,
    ENUM_MSG_TYPE_FLUSH_FILE_RESPOND,
    ENUM_MSG_TYPE_MOVE_FILE_REQUEST,
    ENUM_MSG_TYPE_MOVE_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_RESPOND,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_REQUEST,
    ENUM_MSG_TYPE_UPLOAD_FILE_DATA_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_RESPOND,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_REQUEST,
    ENUM_MSG_TYPE_SHARE_FILE_AGREE_RESPOND,
    ENUM_MSG_TYPE_DELETE_DIR_REQUEST, 
    ENUM_MSG_TYPE_DELETE_DIR_RESPOND, 
    ENUM_MSG_TYPE_DELETE_FILE_REQUEST,  
    ENUM_MSG_TYPE_DELETE_FILE_RESPOND, 
    ENUM_MSG_TYPE_RENAME_REQUEST,       
    ENUM_MSG_TYPE_RENAME_RESPOND,       
    ENUM_MSG_TYPE_DOWNLOAD_FILE_REQUEST,    
    ENUM_MSG_TYPE_DOWNLOAD_FILE_RESPOND,   
    ENUM_MSG_TYPE_DOWNLOAD_FILE_DATA_RESPOND,  
    ENUM_MSG_TYPE_MAX=0x00fffffff,
};
struct PDU{//协议数据单元结构体
    uint uiPDULen;//协议总长度
    uint uiMsgLen;//实际消息长度（柔性数组）
    uint uiType;//消息类型
    char caData[64];//参数
    char caMsg[];//实际消息
};

struct FileInfo{
    char caName[32];
    int iType;
};

PDU* mkPDU(uint uiMsgLen = 0);
#endif // PROTOCOL_H
